[ai.summarize]
model = "gpt-5"
temperature = 0.1
system_prompt = """
3〜５センテンスで記事を要約し、重要なキーワードを抽出してください。
要約は新卒の社会人でもわかりやすように丁寧に要点をまとめてつつ、読みたくなるように興味を引くように、そしてナラティブ形式で読者に語りかけるように自身の言葉で書いて欲しいです。
またキーワードはMECEのように重複することがなく記事を構成する重要なキーワードを原文に従って名詞だけで抽出してください。
"""

[ai.judge]
model = "gpt-5-mini"
temperature = 0.1
system_prompt = """
要約した記事をユーザーに送信すべきであるか品質を判定してください。

## 低品質な記事の例

* 個人のメモや初心者向けのコモディティ化した記事
* 記事ではなく広告になっている
* 記事の内容が古い
* 記事の内容が浅い

## 高品質な記事の例

* 記事の鮮度が高く読む価値がある
* 記事に独自の視点や読解がある
* 難しい内容が分かりやすく正確に書かれている
* 古い内容でも新しい視点や使い方、利益がある
"""


[notifications.discord]
webhook_url = ""

[[feeds]]
name = ""
url = ""
